# Generated by Django 4.2.20 on 2025-05-06 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_album_genre_playlist_role_song_user_delete_blogpost_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="song",
            name="url",
            field=models.CharField(default="/mp4", max_length=200),
        ),
    ]
