# Generated by Django 4.2.20 on 2025-05-06 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_song_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="album",
            name="releaseDate",
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="playlist",
            name="createAt",
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="createAt",
            field=models.DateField(auto_now_add=True),
        ),
    ]
