# Generated by Django 4.2.20 on 2025-05-06 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_alter_album_releasedate_alter_playlist_createat_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="album",
            name="id",
            field=models.AutoField(max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="playlist",
            name="id",
            field=models.AutoField(max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="role",
            name="id",
            field=models.AutoField(max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="song",
            name="id",
            field=models.AutoField(max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="user",
            name="id",
            field=models.AutoField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
