# Generated by Django 4.2.20 on 2025-05-14 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0006_alter_album_id_alter_playlist_id_alter_role_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="email",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
