# Generated by Django 4.2.20 on 2025-05-14 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0007_user_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="song",
            name="url",
            field=models.FileField(blank=True, null=True, upload_to="songs/"),
        ),
    ]
