# Generated by Django 4.2.20 on 2025-05-16 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0008_alter_song_url"),
    ]

    operations = [
        migrations.RenameField(
            model_name="album",
            old_name="user",
            new_name="creator",
        ),
        migrations.RemoveField(
            model_name="song",
            name="album",
        ),
        migrations.AddField(
            model_name="album",
            name="poster",
            field=models.ImageField(blank=True, null=True, upload_to="posters/"),
        ),
        migrations.AddField(
            model_name="playlist",
            name="poster",
            field=models.ImageField(blank=True, null=True, upload_to="posters/"),
        ),
        migrations.AddField(
            model_name="song",
            name="albums",
            field=models.ManyToManyField(related_name="songs", to="api.album"),
        ),
        migrations.AddField(
            model_name="song",
            name="artists",
            field=models.ManyToManyField(related_name="songs", to="api.user"),
        ),
        migrations.AddField(
            model_name="song",
            name="thumbnail",
            field=models.ImageField(blank=True, null=True, upload_to="thumbnails/"),
        ),
    ]
