# Generated by Django 4.2.20 on 2025-05-16 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0009_rename_user_album_creator_remove_song_album_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="song",
            name="genre",
        ),
        migrations.AddField(
            model_name="song",
            name="genre",
            field=models.ManyToManyField(blank=True, to="api.genre"),
        ),
    ]
