# Generated by Django 4.2.20 on 2025-05-17 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0011_user_groups_user_is_active_user_is_staff_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="fullname",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
