# Generated by Django 4.2.20 on 2025-05-17 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0012_user_fullname"),
    ]

    operations = [
        migrations.AddField(
            model_name="song",
            name="play_count",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
